[camera]
fFieldOfView = 70.0
fMovementSpeed = 10.0
fRotationSpeed = 0.25

[renderer]
iChunkDataBufferSize = 33554432

[window]
iHeight = 720
iWidth = 1280
sTitle = 'voxel-game'

[world]
iLoadDistance = 4
